# ruff: noqa: E501
# fmt: off
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
import numpy as np
from block_slope_breadth_core import ART,ART_HASH,FEE,FULL,HASH,OOS,TRAIN,bootstrap,boundaries,breadth,features,load,metrics,pack,positions,sharpe

def feature_summary(f,span,entry,exit_):
    vals=[(m,b) for t,(m,b,_) in f.items() if span[0]<=t<span[1]]; m=np.array([x[0] for x in vals]); b=np.array([x[1] for x in vals]); pos=m>0; neg=m<0; ent=pos&(b>=entry); ex=neg&(b<=exit_); ent_ex=pos&(b<entry); ex_delay=neg&(b>exit_)
    return {"daily_decisions":len(vals),"positive_median_rate":float(pos.mean()),"negative_median_rate":float(neg.mean()),"breadth_mean":float(b.mean()),"breadth_median":float(np.median(b)),"breadth_q30_lower":int(np.quantile(b,.30,method="lower")),"breadth_q70_higher":int(np.quantile(b,.70,method="higher")),"entry_condition_rate":float(ent.mean()),"exit_condition_rate":float(ex.mean()),"entry_exclusion_rate_given_positive_median":float(ent_ex[pos].mean()) if pos.any() else None,"exit_delay_rate_given_negative_median":float(ex_delay[neg].mean()) if neg.any() else None,"entry_breadth_gate_degenerate":bool(pos.any() and not ent_ex.any()),"sign_breadth_conflict_rate":float((ent_ex|ex_delay).mean())}

def diagnostics(d,f,bound,pos,packed):
    a,z=OOS; entry=int(bound["entry_breadth_q70_higher"]); exit_=int(bound["exit_breadth_q30_lower"]); cp=pos["candidate"]; c=cp[a:z]; b1=pos["b1"][a:z]; market=packed["candidate"][4][a:z]; conly=(c==1)&(b1==0); bonly=(c==0)&(b1==1); net=packed["candidate"][0][a:z]
    transitions=[]
    for t,(median,breadth_value,_) in f.items():
        if not a<=t<z: continue
        j=t+1
        if j>=len(cp) or cp[j-1]==cp[j]: continue
        rel=j-a; forward=None if rel+168>len(market) else float(np.prod(1+market[rel:rel+168])-1); transitions.append(("entry" if cp[j]==1 else "exit",forward))
    entries=[v for kind,v in transitions if kind=="entry" and v is not None]; exits=[v for kind,v in transitions if kind=="exit" and v is not None]
    bounds=np.r_[0,np.flatnonzero(np.diff(c)!=0)+1,len(c)]; eps=[]
    for l,r in zip(bounds[:-1],bounds[1:],strict=True):
        if c[l]==1: eps.append((r-l,float(np.prod(1+net[l:r])-1)))
    worst=lambda h: float(min(np.prod(1+net[i:i+h])-1 for i in range(len(net)-h+1)))
    return {"feature_drift":{"training":feature_summary(f,TRAIN,entry,exit_),"development_oos":feature_summary(f,OOS,entry,exit_)},"candidate_only_hours":int(conly.sum()),"candidate_only_market_gross_sum":float(market[conly].sum()),"b1_only_hours":int(bonly.sum()),"b1_only_market_gross_sum":float(market[bonly].sum()),"entry_count_oos":sum(k=="entry" for k,_ in transitions),"exit_count_oos":sum(k=="exit" for k,_ in transitions),"post_entry_positive_168h_ratio":float(np.mean(np.array(entries)>0)) if entries else None,"post_exit_negative_168h_ratio":float(np.mean(np.array(exits)<0)) if exits else None,"complete_entry_windows":len(entries),"complete_exit_windows":len(exits),"worst_rolling_168h_candidate_return":worst(168),"worst_rolling_720h_candidate_return":worst(720),"episodes":{"overlapping_oos_episodes":len(eps),"median_duration_hours":float(np.median([x[0] for x in eps])) if eps else None,"profitable_episode_ratio":float(np.mean(np.array([x[1] for x in eps])>0)) if eps else None,"worst_episode_return":min((x[1] for x in eps),default=None)}}

def main():
    p=argparse.ArgumentParser(); p.add_argument("--btc-csv",type=Path,required=True); p.add_argument("--eth-csv",type=Path,required=True); p.add_argument("--output",type=Path,required=True); a=p.parse_args(); frames={"BTC-USDT":load(a.btc_csv,"BTC-USDT"),"ETH-USDT":load(a.eth_csv,"ETH-USDT")}
    result={"family_id":"robust-block-slope-breadth-hysteresis-1h-v1","canonical_signature":"robust-block-slope-breadth-hysteresis-1h-v1|own-history-only|window=2160H|blocks=12x180H-contiguous-nonoverlap|block-slope=log(close_end/close_start)/180|median=NumPy-even-median|breadth=count(slope>0)|entry=median>0-and-breadth>=train-q70-higher|exit=median<0-and-breadth<=train-q30-lower|otherwise-carry|stateful|daily-00UTC|next-open|fee=5bps-one-way|candidate=1|grid=0","issue":637,"research_parent":"5a0fcc97d1a882f8223656c51f5bb8055f534e38","runner_sha256":hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),"candidate_count":1,"parameter_grid_count":0,"canonical_fee_one_way":FEE,"sample":{"training":list(TRAIN),"development_oos":list(OOS),"full_scored":list(FULL),"fold_count":12,"fold_hours":2160,"parsed_prefix_bars":43441,"later_suffix_unread":True},"sources":{m:{"workflow_run_id":30401519824,"artifact_id":ART[m],"artifact_zip_sha256":ART_HASH[m],"csv_sha256":HASH[m],"source_total_observations":43941} for m in HASH},"feature":{"window_hours":2160,"block_count":12,"block_hours":180,"block_slope":"log(close_end/close_start)/180","median":"NumPy even-sample median","positive_breadth":"count(block_slope > 0)"},"diagnostic_repair":{"conditional_selector_rates_added":True,"strategy_outputs_changed":False},"markets":{}}
    accepted=True
    for market,d in frames.items():
        f=features(d); bound=boundaries(f); pos=positions(d,f,int(bound["entry_breadth_q70_higher"]),int(bound["exit_breadth_q30_lower"])); packed={k:pack(d,v) for k,v in pos.items()}; spans=(("training",TRAIN),("development_oos",OOS),("full_scored",FULL)); allm={label:{k:metrics(packed[k],pos[k],span) for k in pos} for label,span in spans}; cn,b0n,b1n=packed["candidate"][0],packed["b0"][0],packed["b1"][0]; br=breadth(cn,d.index); bt=bootstrap(cn,b1n); rb0=sharpe(cn[OOS[0]:OOS[1]]-b0n[OOS[0]:OOS[1]]); rb1=sharpe(cn[OOS[0]:OOS[1]]-b1n[OOS[0]:OOS[1]]); c=allm["development_oos"]["candidate"]; b1=allm["development_oos"]["b1"]
        gates={"positive_net_return":c["net_return"]>0,"positive_sharpe":c["sharpe"] is not None and c["sharpe"]>0,"profitable_folds_at_least_7_of_12":br["profitable_folds"]>=7,"profitable_years_at_least_3":br["profitable_years"]>=3,"positive_fold_concentration_at_most_50pct":br["positive_fold_concentration"] is not None and br["positive_fold_concentration"]<=.5,"max_drawdown_within_2pp_of_b1":c["max_drawdown"]>=b1["max_drawdown"]-.02,"turnover_no_greater_than_b1":c["turnover"]<=b1["turnover"],"positive_edge_per_turnover":c["edge_per_turnover_bps"] is not None and c["edge_per_turnover_bps"]>0,"edge_per_turnover_no_worse_than_b1":c["edge_per_turnover_bps"] is not None and c["edge_per_turnover_bps"]>=b1["edge_per_turnover_bps"],"net_return_no_worse_than_b1":c["net_return"]>=b1["net_return"],"sharpe_no_worse_than_b1":c["sharpe"] is not None and c["sharpe"]>=b1["sharpe"],"positive_residual_sharpe_vs_b1":rb1 is not None and rb1>0,"bootstrap_mean_delta_lower_bound_positive":bt["annualized_mean_delta"]["lower_95"]>0,"bootstrap_sharpe_delta_lower_bound_positive":bt["sharpe_delta"]["lower_95"]>0,"source_chronology_timing_fee_checks":True}; ok=all(gates.values()); accepted&=ok; result["markets"][market]={"training_boundaries":bound,"metrics":allm,"breadth":br,"residual_sharpe_vs_b0":rb0,"residual_sharpe_vs_b1":rb1,"bootstrap_vs_b1":bt,"diagnostics":diagnostics(d,f,bound,pos,packed),"acceptance_gates":gates,"accepted":ok}
    result["accepted"]=accepted; result["verdict"]="accept_for_g1_nomination" if accepted else "reject_exact_robust_block_slope_breadth_hysteresis_family"; a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(result,indent=2,sort_keys=True)+"\n")
if __name__=="__main__": main()
